### ISSUE TITLE
wildcard and none wildcard cert from same domain issues "TXT record .. already exists ..." 

### ISSUE THREAD

**Issue by kagithd** [couchtyp/certbot-dns-schlundtech#3] opened 2018-10-11 06:11 UTC
I'm trying to get a certificate with -d *.domain.de -d domain.de

this is for getting a correct https redirect from  domain.de -> whatever.domain.de

in this combination i got an Error 
...
Cleaning up challenges
TXT record _acme-challenge.domain.de for domain.de already exists with different value

the former manual setup (copy / paste)  TXT record to schlund-tech web-config is working 

---
Thanks for your Work!

**Comment by couchtyp** [comment] 2018-10-11 06:43
The problem seems to be that the same dns name (_acme-challenge) is used for both, which in theory should work, but apparently doesn't.

I will have a look into it.

**Comment by couchtyp** [comment] 2018-10-11 10:11
So, I confirmed that for `*.domain.de` and `domain.de` certbot requests `_acme-challenge.domain.de` to be set up with different values, then checks them afterwards. The plugin unnecessarily checks for TXT records already present for the domain, which leads to the message you received.

This will be fixed soon.

**Closed as completed** 2018-10-11 18:12 UTC
Labels: bug

**Comment by couchtyp** [comment] 2018-10-11 18:17
Issue has been fixed.
DNS challenges for the same domain will now correctly add multiple TXT records to the respective zone.

**Comment by kagithd** [comment] 2018-10-12 06:55
works like a charm, thanks a lot !
